name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: |
          cd packages/ts
          npm install -g pnpm
          pnpm install

      - name: Build TS library
        run: |
          cd packages/ts
          pnpm build
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
