name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - "packages/ts/**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: |
          cd packages/ts
          npm install -g pnpm
          pnpm install
      - name: Authenticate with NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

      - name: Build TS library
        run: |
          cd packages/ts
          pnpm build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
